#!/usr/bin/env bash

set -e 

VOLUME="mongodata3.4"
NAME="mongo3.4"

docker build -t $NAME ./mongo3.4

docker stop $NAME || true
docker rm $NAME || true

docker run \
  -d \
  --name $NAME \
  --restart always \
  -p 27017:27017 \
  -v $VOLUME:/data/db \
  $NAME
