#!/usr/bin/env bash

set -e

source ./common

if test -z "$POSTGRES_ROOT_PASSWORD"
then
  echo "\$POSTGRES_ROOT_PASSWORD variable not found"
  echo "Pleas define \$POSTGRES_ROOT_PASSWORD in your shell initialiaztion scripts like bash_profile"
  exit 1
fi

if test -z "$PGHERO_DB"
then
  echo "\$PGHERO_DB variable not found"
  echo "Pleas define the name of the DB to connect with \$PGHERO_DB variable just befor this run command"
  echo "Example:"
  echo "PGHERO_DB=app_development ./pghero/run"
  exit 1
fi

NAME=pghero--$PGHERO_DB

docker stop $NAME > /dev/null 2>&1 || true
docker rm $NAME > /dev/null 2>&1 || true
docker run --name $NAME \
  --restart always \
  -e DATABASE_URL=postgres://postgres:$POSTGRES_ROOT_PASSWORD@postgres9.6:5432/$PGHERO_DB \
  --network $CONTAINERS_LOCAL_NETWORK \
  -p 5454:8080 \
  -d \
  ankane/pghero

echo "You can access pghero for ${PGHERO_DB} DB at http://localhost:5454"
