#!/usr/bin/env bash

set -e

VOLUME=clustercontrol-data
NAME=clustercontrol

docker stop $NAME > /dev/null 2>&1 || true
docker rm $NAME > /dev/null 2>&1 || true
docker run --name $NAME \
  -h clustercontrol \
  --restart always \
  -e POSTGRES_PASSWORD=root \
  -p 5000:80 \
  -p 5001:443 \
  -v /storage/clustercontrol/cmon.d:/etc/cmon.d \
  -v /storage/clustercontrol/datadir:/var/lib/mysql \
  -v /storage/clustercontrol/sshkey:/root/.ssh \
  -v /storage/clustercontrol/cmonlib:/var/lib/cmon \
  -v /storage/clustercontrol/backups:/root/backups \
  -d \
  severalnines/clustercontrol
