#!/usr/bin/env bash

set -e

CONTAINER_NAME=postgres9.6

docker exec -ti $CONTAINER_NAME apt-get update
docker exec -ti $CONTAINER_NAME apt-get install -y openssh-server openssh-client
docker exec -it $CONTAINER_NAME sed -i 's|^PermitRootLogin.*|PermitRootLogin yes|g' /etc/ssh/sshd_config
docker exec -it $CONTAINER_NAME sed -i 's|^#PermitRootLogin.*|PermitRootLogin yes|g' /etc/ssh/sshd_config
docker exec -ti $CONTAINER_NAME service ssh start
docker exec -ti $CONTAINER_NAME passwd

echo "DB IP address is:"
docker inspect $CONTAINER_NAME | grep IPAddress
